### ISSUE TITLE
add <names> as optional (first) child in <groups>

### ISSUE THREAD

**Issue by riedde** [Edirom/edirom-edition-schema#7]
The names section should also be allowed on groups-level. The edirom is able to render it as shown on the attached image.

For now the occurance of `//groups/names` is invalid.
```
<concordance name="Edition">
               <names>
                  <name xml:lang="de">Edition</name>
                  <name xml:lang="en">Edition</name>
               </names>
               <groups label="Song">
                  <names>
                     <name xml:lang="de">Lied</name>
                     <name xml:lang="en">Song</name>
                  </names>
                  <group>
                     <names>
                        <name xml:lang="de">Trüber Abschied</name>
                        <name xml:lang="en">Trüber Abschied</name>
                     </names>
                     <connections label="Takt"/>
```
<img width="321" alt="Bildschirmfoto 2022-01-19 um 12 50 26" src="https://user-images.githubusercontent.com/27779797/150124560-7663c5b6-8a31-4c89-a59d-c479ee9d6a65.png">

**Comment by bwbohl** [comment]
@riedde thx for bringing it up!

**Comment by bwbohl** [comment]
I just noticed that groups may contain `labels/label` (which is an heirloom from v1.2) but as a search in the Edirom Online repo revealed is not processed Edirom Online (https://github.com/Edirom/Edirom-Online/search?q=edirom%3Alabel). So this should be removed at the same time.

**Comment by bwbohl** [comment]
fixed in 666343b

**Comment by riedde** [comment]
Just as an example: This could be helpful when edition a work collection of songs and duets.  So their genre can be displayed if necessary.

**Comment by bwbohl** [comment]
> Just as an example: This could be helpful when edition a work collection of songs and duets. So their genre can be displayed if necessary.

this example should be added to some documentation somewhere
